module.exports = {
  STYLIZE_STARTED: 'STYLIZE_STARTED',
  STYLIZE_SUCCEEDED: 'STYLIZE_SUCCEEDED',
  STYLIZE_ERROR: 'STYLIZE_ERROR',
  UPLOAD_STARTED: 'UPLOAD_STARTED',
  UPLOAD_SUCCEEDED: 'UPLOAD_SUCCEEDED',
  UPLOAD_ERROR: 'UPLOAD_ERROR'
}